[book]
authors = ["Adèle Pluquet"]
language = "en"
multilingual = false
src = "src"
title = "3D Cartography with a drone - Documentation"

[output.html]

git-repository-url = "https://github.com/mitsio-motu-data/3D-Cartography-Drone"
