[book]
authors = ["Adèle Pluquet"]
language = "en"
multilingual = false
src = "src"
title = "Cartographie 3D avec un drone - Documentation"

[output.html]
default-theme = "mitsiomotu"
preferred-dark-theme = "mitsiomotu-dark"
site-url = "/3D-Cartography-Drone/"
git-repository-url = "https://github.com/mitsio-motu-data/3D-Cartography-Drone"
