[book]
authors = ["Adèle Pluquet"]
language = "en"
multilingual = false
src = "src"
title = "Cartographie 3D avec un drone - Documentation"

[output.html]
site-url = "/3D-Cartography-Drone/"
git-repository-url = "https://github.com/mitsio-motu-data/3D-Cartography-Drone"

[output.html.redirect]
"index.html" = "introduction/presentation_projet/presentation_projet.html"
