name: github pages

on:
  # Define the GitHub Events to trigger the workflow
  push:
    branches: main
    paths: Documentation/**
  pull_request:
    paths: Documentation/**

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build with mdBook
        run: mdbook build Documentation

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Documentation/book